### ISSUE TITLE
Unregistered Uservoice Links

### ISSUE THREAD

**Issue by Azrael-Azzy** [SteamingMutt/DiscordFeedback#115]
Links such as: ones posted by anonymous users 
ex. https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/16388104-in-google-chrome-not-working-sounds-and-audio-chat
or ones posted with only the subject and no description 
ex. https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/18797434-rfworld
aren't registered with the bot

**Comment by SteamingMutt** [comment]
Fixed with https://github.com/SteamingMutt/DiscordFeedback/commit/70787175c6fb40ab771151f21f37ed9fe5efddc5
