### ISSUE TITLE
Can't merge dupes if original is anonymous

### ISSUE THREAD

**Issue by Azrael-Azzy** [SteamingMutt/DiscordFeedback#123]
Can't merge suggestions from UV if the original link is authored by an anonymous user
eg.!dupe https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/20626810-replace-video-call-button-with-screen-share-call-b https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/20517223-screen-sharing-without-a-camera

**Comment by ThaTiemsz** [comment]
On it
